name:                minotaur
version:             0.1.0.0
github:              "Aldrog/haskell-playground"
license:             BSD3
author:              "Andrew Penkrat"
maintainer:          "contact.aldrog@gmail.com"
copyright:           "2020 Andrew Penkrat"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Aldrog/haskell-playground#readme>

dependencies:
- base >= 4.7 && < 5
- array
- tagged

library:
  source-dirs: src

executables:
  minotaur-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minotaur

tests:
  minotaur-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minotaur
